name: aaa
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0

  flutter_animate: ^4.3.0
  cupertino_icons: ^1.0.8
  qr_code_scanner_plus: ^2.0.10+1
  mobile_scanner: ^6.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-Black.otf
          weight: 600
        - asset: assets/fonts/Inter-V.ttf
          weight: 400
  assets:
    - assets/logo.png
    - assets/close.png
    - assets/done_blue.png
